### ISSUE TITLE
Create a script for extracting features from the RAVDESS dataset

### ISSUE THREAD

**Issue by VMois** [bme-ai/speech-emotion-analysis#2]
All audio files from RAVDESS will be placed in a single directory. We need to write a script to extract features from every file and save it to parquet file. Probably, using pandas and pyarrow.

**Comment by themreza** [comment]
I have created `feature_extraction.py` and `tests/view_parquet.py`, updated `README.md` with information about setting up the environment through Conda and instructions on running the scripts. I also copied Vlad's env.yml.

All we need to do now to get the audio features extracted is install conda and activate the environment, and create a folder called `raw-data` and copy the two zip files downloaded from RAVDESS there. https://imgur.com/dpy4wLB

Then we can run `python feature_extraction.py`. This will automatically extract the zip files into `raw-data`, use LibROSA to analyze and extract the features, and finally the results with columns `filename`, `gender`, `emotion`, and `features` into a file called `audio-features.parquet.gzip` in the main directory.

Since there isn't a good parquet viewer program out there, I wrote our own parquet viewer which shows the contents of `audio-features.parquet.gzip` by running `tests/view_parquet.py`.

Here are some screenshots of the scripts running:
* https://imgur.com/lkXDR1i
* https://imgur.com/yvqVHzf
* https://imgur.com/cuNvigK
* https://imgur.com/1qGDNVm

**Comment by VMois** [comment]
The issue cannot be closed until related PR won't be accepted.

**Comment by themreza** [comment]
I've marked the engine as `pyarrow`, removed gzip compression and parquet viewer.
We need to merge this version of README.md since it includes your edits and contains clear instructions on what machine types can run this project (32 bit can't) as well as steps on extracting the features.

**Comment by VMois** [comment]
Thanks. I will add my changes to your README and merge everything.
