### ISSUE TITLE
Update feature_extraction script

### ISSUE THREAD

**Issue by VMois** [bme-ai/speech-emotion-analysis#7]
To be able to load more datasets in future we need to refactor existing feature_extraction script. To Do list to discuss:

- rename the script to `ravdess_feature_extraction.py` and move it to `etl/` folder. Later, we will be able to add more scripts related to data transformation

-  we must separate test and train examples during extraction, not during the training. It will ensure that train and test data always the same for different versions of the neural network.

- update README instructions

- more?

Please, add your comments and ideas.

Final tasks list:

- [x] rename the script to `ravdess.py` and move it to `features_extraction_scripts/` folder
- [x] update `ravdess.py`  to separate test and train examples during extraction
- [x] create `features_extraction_scripts/utils.py` file for keeping common used function to extract data
- [x] create a single script to run all extraction scripts at once
- [x] update README desciption
- [x] create separate folders for train and test data

**Comment by themreza** [comment]
Why the etl folder? What does it stand for?

It's much easier to have one main script where we can pass command line arguments and choose the libraries we want it to extract. Like `python feature_extraction.py -ravdess -otherlibrary`. 

Let me know what the actual ratio for separation of the training and test data is. Even better, make a sketch of the final Parquet file we're looking for?

**Comment by VMois** [comment]
ETL (Extract-Transform-Load), generally, a common name for the tasks related to loading data, then process/transform it and save to a database, data lake, etc. 

I want to keep scripts related to data extraction in a separate folder, in separate files. First reason, we won't need to write additional code for passing arguments. Second, we won't have one big file with everything. If you want to have some common functions, we can create `etl/utils.py` file and keep commonly used there.

The standard for data separation is 80% for the train, and 20% for the test (don't need to be exactly the 80/20, but very close to it). It would be great to have all datasets automatically split into train and test during extraction. We another idea is to keep them in folders `data/test` and `data/train`, so during training, we won't play and separate it etc. Also, every dataset will have the test and train the parquet file.

What do you think?

**Comment by themreza** [comment]
If we're going to use any name convention, we have to clearly label and explain the meaning behind the abbreviations. If it's confusing to the developers, it'll be much worse to others. 

There's a reason why having a single script is advantageous. Firstly, since we're handling multiple datasets, it is crucial for us to have a unified output data structure in Parquet. If we have multiple scripts, it creates room for error and data corruption as one script writes something to the dataset and another will try to amend or update it. Secondly, having multiple copies of extractors means repeated code and in case there are any changes to be made in one script, all the others need to be modified as well, which again introduces problems. Finally, with the single script, all the processing is done in one pass and a clean Parquet file is generated at the end. Passing arguments is much more efficient than running multiple scripts. 

Again, since we're taking in simple arguments, we can change the training and testing ratios as an option while executing the command. The single script automatically achieves exactly what you said.

**Comment by VMois** [comment]
1. ETL is common used name, but, agree, that some people could not be familiar with naming. We can use something like `feature_extraction/` or similar.
2. It's not a problem to have unified output to Parquet files. As I told earlier, we can create `feature_extraction/utils.py` file and handle all commonly used methods there. For example, we can have unified function for saving data to Parquet file. This also addresses your comment about repeated code, in addition, every dataset is different in term of export.
3. About code modification issue. Using arguments, we will get the same problem. For different arguments, we will have different functions to handle different dataset. One major change in one function, changes in all of them.
4. About single clear Parquet file. I don't want to use single file. The structure I have in my mind looks like this:

- we have two folder `train/` and `test/`
- every new dataset will be split in two files. Example: `train/ravdess.parquet` and `test/ravdess.parquet`. In this situation, no corruption will happen if new datasets will be added. Later, during the training we will be able to load all of the datasets or a few by choosing different parquet files. All parquet files will have the same format.

5. We don't really need ratio parameter. 80/20 is a standard and will be enough for now.

@samerbahri join discussion :)

**Comment by themreza** [comment]
Fine. We just have to make sure the conventions are explained in the ReadMe. I agree with creating a utilities class/file that we can import in other places too. The folder structure sounds reasonable. @samerbahri what do you think?

**Comment by VMois** [comment]
@themreza about folder structure. Pyarrow support imports from the multiple files in the folder like `pq.read_pandas('train/').to_pandas()` .

Also, it would be great to recheck our feature extraction, because our results on training are very bad (I know we have less data, but even with this in mind, we have very poor accuracy).

I will update the tasks list in this issue.

**Comment by themreza** [comment]
@VMois There shouldn't be a mistake in there, or at least not something major since the actual processing part is directly mirrored from our guide repo. The reason why we're getting different results is most likely that we're simply trying to copy-paste the same commands they used but since our data structure is different it produces incorrect results.

**Comment by VMois** [comment]
Could be possible. Really, I only have an assumption about why performance is so poor. Hope, this small refactoring will give us some insight.
